default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: g2-rails-practice-task-new_list-development

test:
  <<: *default
  database: g2-rails-practice-task-new_list-test
